first_nine_weeks = [
  # Week 1 - Beginning of the Year
  {"day": 1, "title": "Classroom Rituals and Routines", "teks": [], "lab": False},
  {"day": 2, "title": "Science Notebook and Lab Notebook Setup", "teks": [], "lab": False},
  {"day": 3, "title": "Introduction to Science Tools and Equipment", "teks": ["5.1A", "5.1B"], "lab": True},
  {"day": 4, "title": "Lab Safety", "teks": ["5.1C"], "lab": True},

  # Unit 1 - Investigating Physical Properties of Matter
  {"day": 5, "title": "Matter and Physical Properties", "teks": ["5.6A"], "lab": False},
  {"day": 6, "title": "States of Matter", "teks": ["5.6A"], "lab": False},
  {"day": 7, "title": "Magnetism", "teks": ["5.6A"], "lab": True},
  {"day": 8, "title": "Mass", "teks": ["5.6A"], "lab": False},
  {"day": 9, "title": "Volume", "teks": ["5.6A"], "lab": False},
  {"day": 10, "title": "Mass and Volume Investigation", "teks": ["5.6A"], "lab": True},
  {"day": 11, "title": "Objects in Liquids", "teks": ["5.6A"], "lab": True},
  {"day": 12, "title": "Liquids in Liquids", "teks": ["5.6A"], "lab": True},
  {"day": 13, "title": "Soluble and Insoluble Materials", "teks": ["5.6A"], "lab": True},
  {"day": 14, "title": "Conductors and Insulators", "teks": ["5.6A"], "lab": True},
  {"day": 15, "title": "Matter Review and Performance Assessment", "teks": ["5.6A"], "lab": False},

  # Unit 2 - Investigating Mixtures
  {"day": 16, "title": "What Is a Mixture?", "teks": ["5.6B"], "lab": True},
  {"day": 17, "title": "Separating Mixtures by Particle Size", "teks": ["5.6B"], "lab": True},
  {"day": 18, "title": "Separating Mixtures Using Magnetism", "teks": ["5.6B"], "lab": True},
  {"day": 19, "title": "Separating Mixtures Using Relative Density", "teks": ["5.6B"], "lab": True},
  {"day": 20, "title": "Solubility and Solutions in Mixtures", "teks": ["5.6B"], "lab": True},
  {"day": 21, "title": "Separating Solutions by Evaporation", "teks": ["5.6B"], "lab": True},
  {"day": 22, "title": "Conservation of Matter in Solutions", "teks": ["5.6B"], "lab": True},
  {"day": 23, "title": "Mixtures and Solutions Review", "teks": ["5.6B"], "lab": True},
  {"day": 24, "title": "Matter Is Made of Particles Too Small to See", "teks": ["5.6D"], "lab": True},
  {"day": 25, "title": "Unit 2 Performance Assessment", "teks": ["5.3A", "5.6B", "5.6D"], "lab": True},

  # Unit 3 - Investigating Force and Motion
  {"day": 26, "title": "What Is Force?", "teks": ["5.7A"], "lab": True},
  {"day": 27, "title": "Equal Forces and Balanced Motion", "teks": ["5.7A"], "lab": True},
  {"day": 28, "title": "Unequal Forces and Changes in Motion", "teks": ["5.7A"], "lab": True},
  {"day": 29, "title": "Pushes, Pulls, Strength, and Direction", "teks": ["5.7A"], "lab": True},
  {"day": 30, "title": "Gravity", "teks": ["5.7A"], "lab": True},
  {"day": 31, "title": "Friction", "teks": ["5.7A"], "lab": True},
  {"day": 32, "title": "Magnetism as a Force", "teks": ["5.7A"], "lab": True},
  {"day": 33, "title": "Mechanical Energy and Energy Transfer", "teks": ["5.7A"], "lab": True},
  {"day": 34, "title": "Variables in Force and Motion Investigations", "teks": ["5.7B", "5.1B", "5.1E"], "lab": True},
  {"day": 35, "title": "Testing Variables and Graphing Data", "teks": ["5.7B", "5.1B", "5.1E"], "lab": True},
  {"day": 36, "title": "Car on a Ramp Investigation", "teks": ["5.7B", "5.1B", "5.1E"], "lab": True},
  {"day": 37, "title": "Balloon Rocket Investigation", "teks": ["5.7B", "5.1B", "5.1E"], "lab": True},
  {"day": 38, "title": "Design Your Own Lab: Which Ball Bounces Higher?", "teks": ["5.7B", "5.1B", "5.1E"], "lab": True},
  {"day": 39, "title": "Analyze Ball Bounce Data and Make Graphs", "teks": ["5.7B", "5.1B", "5.1E"], "lab": True},
  {"day": 40, "title": "Playground Equipment Engineering Challenge", "teks": ["5.7A", "5.7B", "5.1B", "5.1E"], "lab": True},
  {"day": 41, "title": "Unit 3 Performance Assessment and Presentation", "teks": ["5.7A", "5.7B", "5.1B", "5.1E", "5.3A"], "lab": True},
  {"day": 42, "title": "1st 9 Weeks STAAR Spiral Review", "teks": ["5.6A", "5.6B", "5.6D", "5.7A", "5.7B"], "lab": True},
  {"day": 43, "title": "1st 9 Weeks Science Stations Review", "teks": ["5.6A", "5.6B", "5.6D", "5.7A", "5.7B"], "lab": True},
  {"day": 44, "title": "1st 9 Weeks Assessment and STAAR-Style Practice", "teks": ["5.6A", "5.6B", "5.6D", "5.7A", "5.7B"], "lab": True},
  {"day": 45, "title": "Data Reflection, Notebook Check, Catch-Up, and Preview Next Unit", "teks": ["5.6A", "5.6B", "5.6D", "5.7A", "5.7B"], "lab": True},

]