def make_lesson(
    day,
    title,
    unit,
    teks,
    focus,
    vocabulary=None,
    materials=None,
    lab_link=None,
    lab_link_text=None,
    mcgraw_hill=None,
):
    vocabulary = vocabulary or []
    materials = materials or []

    lesson = {
        "day": day,
        "title": title,
        "unit": unit,
        "teks": teks,
        "focus": focus,
        "overview": focus,
        "learning_target": f"I can {focus[0].lower() + focus[1:] if focus else 'learn today’s science skill.'}",
        "bell_ringer": "What do you already notice, know, or wonder about today’s science topic?",
        "mini_lesson": [
            "Introduce the science idea using a short phenomenon, model, image, or teacher demonstration.",
            "Connect the lesson to prior learning and important vocabulary.",
            "Model how scientists observe, measure, test, record data, and explain using evidence.",
        ],
        "science_notebook": [
            "Write the lesson title, TEKS, and learning target.",
            "Create a vocabulary box with student-friendly definitions.",
            "Record observations, data, models, or diagrams from the lesson.",
        ],
        "guided_practice": [
            "Students work with a partner or table group to apply the concept.",
            "Teacher circulates, asks questions, and checks for misconceptions.",
            "Students explain their thinking using science vocabulary.",
        ],
        "lab": [
            "Students complete a hands-on or digital investigation connected to the lesson.",
            "Students collect evidence and use it to explain what happened.",
        ],
        "lab_notebook": [
            "Question",
            "Prediction",
            "Materials",
            "Procedure",
            "Data / Observations",
            "Claim",
            "Evidence",
            "Reasoning",
        ],
        "staar_practice": [
            "Students answer a STAAR-style question connected to today’s concept.",
            "Students justify their answer using evidence or vocabulary.",
        ],
        "exit_ticket": "Explain one important idea from today’s lesson using evidence.",
        "vocabulary": vocabulary,
        "materials": materials,
        "teacher_notes": [
            "Keep student responses written, oral, or notebook-based when possible.",
            "Use multiple-choice questions mainly for STAAR practice, not as the only evidence of learning.",
            "Do not copy textbook or copyrighted curriculum pages into the public website. Use this as an original companion resource.",
        ],
    }

    if lab_link:
        lesson["lab_link"] = lab_link
        lesson["lab_link_text"] = lab_link_text or "Open Interactive Lab"

    if mcgraw_hill:
        lesson["mcgraw_hill"] = mcgraw_hill

    return lesson


first_nine_weeks_lessons = [
    # Classroom launch
    make_lesson(
        1,
        "Routines, Safety Contract, and Science Notebook Setup",
        "Classroom Launch",
        "5.1C",
        "follow science routines, understand safety expectations, and set up my science notebook and lab notebook.",
        ["safety", "science notebook", "lab notebook", "procedure", "evidence"],
        ["science notebook", "lab notebook", "safety contract", "pencils", "colored pencils"],
    ),
    make_lesson(
        2,
        "Science Tools, Measuring Tools, and Engineering Design",
        "Classroom Launch",
        "5.1D, 5.1A, 5.1B",
        "choose appropriate science tools and describe how scientists and engineers ask questions, test ideas, and design solutions.",
        ["tool", "measure", "observe", "engineering design", "scientific process", "data"],
        ["balances", "graduated cylinders", "metric rulers", "hand lenses", "thermometers", "spring scales", "safety goggles"],
    ),

    # Unit 1: Physical Properties of Matter
    make_lesson(
        3,
        "What Is Matter? Physical States and Particles",
        "Unit 1: Physical Properties of Matter",
        "5.6A, 5.6D",
        "describe matter, identify solids, liquids, and gases, and explain that matter is made of particles too small to be seen.",
        ["matter", "solid", "liquid", "gas", "particle", "physical state"],
        ["solid objects", "liquids", "balloon or bag of air", "beakers", "hand lenses"],
        "/labs/particles",
        "Open Particle Model Lab",
        "Chapter 3 Lesson 3.3: Particles of Matter; Chapter 2 Lesson 2.4: Solubility and Physical States",
    ),
    make_lesson(
        4,
        "Mass: Measuring Solids, Liquids, and Gases",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "measure and compare mass using grams and explain mass as a physical property of matter.",
        ["mass", "gram", "balance", "digital scale", "heavier", "lighter"],
        ["balances", "digital scale", "objects", "containers", "water"],
        "/labs/balance-scale-mass",
        "Open Balance Scale Simulator",
        "Chapter 2 Lesson 2.1: Mass, Volume and Relative Density",
    ),
    make_lesson(
        5,
        "Volume: Measuring Solids, Liquids, and Gases",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "measure and compare volume using milliliters and water displacement.",
        ["volume", "milliliter", "graduated cylinder", "displacement", "matter"],
        ["graduated cylinders", "water", "small objects", "beakers"],
        "/labs/graduated-cylinder-volume",
        "Open Graduated Cylinder Simulator",
        "Chapter 2 Lesson 2.1: Mass, Volume and Relative Density",
    ),
    make_lesson(
        6,
        "Magnetism: Magnetic or Nonmagnetic?",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "test materials with magnets and classify them as magnetic or nonmagnetic using evidence.",
        ["magnet", "magnetism", "magnetic", "nonmagnetic", "physical property"],
        ["magnets", "paper clips", "coins", "plastic", "wood", "aluminum foil"],
        "/labs/magnetic-or-not",
        "Open Magnetic or Not Lab",
        "Chapter 2 Lesson 2.2: Matter and Magnetism",
    ),
    make_lesson(
        7,
        "Relative Density: Solids in Liquids",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "compare relative density by observing whether solid objects sink or float in water.",
        ["relative density", "sink", "float", "water", "solid", "evidence"],
        ["water", "containers", "wood", "marbles", "rocks", "plastic", "metal objects"],
        "/labs/sink-float",
        "Open Sink or Float Lab",
        "Chapter 2 Lesson 2.1: Mass, Volume and Relative Density",
    ),
    make_lesson(
        8,
        "Relative Density: Liquids in Liquids",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "compare the relative density of liquids by observing how liquids layer.",
        ["relative density", "liquid", "layer", "more dense", "less dense"],
        ["water", "oil", "corn syrup", "honey", "graduated cylinders", "food coloring"],
        "/labs/liquid-density",
        "Open Liquid Density Lab",
        "Chapter 2 Lesson 2.1: Mass, Volume and Relative Density",
    ),
    make_lesson(
        9,
        "Solubility: Soluble Materials",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "test materials in water and identify materials that dissolve as soluble.",
        ["solubility", "soluble", "dissolve", "solution", "water"],
        ["water", "salt", "sugar", "powdered drink mix", "honey", "beakers", "spoons"],
        "/labs/solubility",
        "Open Solubility Lab",
        "Chapter 2 Lesson 2.4: Solubility and Physical States",
    ),
    make_lesson(
        10,
        "Solubility: Insoluble Materials",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "test materials in water and identify materials that do not dissolve as insoluble.",
        ["solubility", "insoluble", "dissolve", "mixture", "evidence"],
        ["water", "oil", "sand", "plastic", "wood", "metal", "beakers"],
        "/labs/solubility",
        "Open Solubility Lab",
        "Chapter 2 Lesson 2.4: Solubility and Physical States",
    ),
    make_lesson(
        11,
        "Conductivity: Thermal and Electrical Energy",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "compare materials based on their ability to conduct or insulate thermal and electrical energy.",
        ["conductor", "insulator", "thermal energy", "electrical energy", "heat"],
        ["safe circuit materials", "teacher demonstration materials", "goggles"],
        "/labs/conductivity",
        "Open Conductivity Lab",
        "Chapter 2 Lesson 2.3: Conductors and Insulators",
    ),
    make_lesson(
        12,
        "Electrical Conductors and Insulators",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "test materials in a simple circuit to determine whether they conduct or insulate electrical energy.",
        ["electrical conductor", "electrical insulator", "circuit", "electricity"],
        ["battery", "wires", "bulb", "safe test materials"],
        "/labs/conductivity",
        "Open Conductivity Lab",
        "Chapter 2 Lesson 2.3: Conductors and Insulators",
    ),
    make_lesson(
        13,
        "Thermal Conductors and Insulators",
        "Unit 1: Physical Properties of Matter",
        "5.6A",
        "compare materials based on how they allow or resist transfer of thermal energy.",
        ["thermal conductor", "thermal insulator", "heat", "temperature", "material"],
        ["teacher demo warm-water setup", "thermometers", "safe materials", "goggles"],
        "/labs/conductivity",
        "Open Conductivity Lab",
        "Chapter 2 Lesson 2.3: Conductors and Insulators",
    ),
    make_lesson(
        14,
        "Comparing Matter and Finding Patterns",
        "Unit 1: Physical Properties of Matter",
        "5.6A, 5.5A",
        "compare matter using multiple physical properties and identify patterns in investigation data.",
        ["compare", "contrast", "classify", "pattern", "physical property"],
        ["data tables", "sample materials", "science notebooks"],
        "/labs/unit1-review",
        "Open Unit 1 Review Game",
    ),
    make_lesson(
        15,
        "Unit 1 Performance Assessment: Toy Material Engineering Challenge",
        "Unit 1: Physical Properties of Matter",
        "5.1C, 5.1G, 5.6A",
        "select materials for a toy design and justify each material using physical properties and evidence.",
        ["engineer", "criteria", "constraint", "material", "evidence"],
        ["toy design planner", "materials chart", "colored pencils", "science notebook"],
        "/labs/unit1-review",
        "Open Unit 1 Review Game",
    ),
    make_lesson(
        16,
        "Unit 1 Reteach, Extension, and Vocabulary Review",
        "Unit 1: Physical Properties of Matter",
        "5.6A, 5.6D",
        "review physical properties of matter and strengthen explanations using vocabulary, data, and CER.",
        ["matter", "physical property", "evidence", "claim", "reasoning"],
        ["vocabulary cards", "notebook", "review stations"],
        "/labs/unit1-review",
        "Open Unit 1 Review Game",
    ),

    # Unit 2: Mixtures
    make_lesson(
        17,
        "What Is a Mixture? Recycling Center Challenge",
        "Unit 2: Mixtures and Solutions",
        "5.6B",
        "explain that mixtures contain substances that can keep their physical properties.",
        ["mixture", "substance", "physical property", "separate", "recycling"],
        ["rocks", "gravel", "sand", "wood chips", "marbles", "iron filings"],
        "/labs/mixtures",
        "Open Mixtures Lab",
        "Chapter 3 Lesson 3.1: Properties of Mixtures",
    ),
    make_lesson(
        18,
        "Separating Mixtures by Magnetism and Size",
        "Unit 2: Mixtures and Solutions",
        "5.6B",
        "separate mixtures using magnetism and particle size and explain why each method works.",
        ["magnetism", "particle size", "sieve", "strainer", "iron filings"],
        ["magnets", "sieves", "screens", "sand", "iron filings"],
        "/labs/magnet-separation",
        "Open Magnet Separation Lab",
        "Chapter 3 Lesson 3.1: Properties of Mixtures",
    ),
    make_lesson(
        19,
        "Separating Mixtures by Filtration and Evaporation",
        "Unit 2: Mixtures and Solutions",
        "5.6B",
        "use filtration and evaporation ideas to explain how mixtures can be separated.",
        ["filter", "filtration", "evaporation", "particle", "separation"],
        ["coffee filters", "beakers", "sand", "water", "saltwater model"],
        "/labs/evaporation",
        "Open Evaporation Lab",
        "Chapter 3 Lesson 3.1: Properties of Mixtures",
    ),
    make_lesson(
        20,
        "What Is a Solution? Create and Compare Solutions",
        "Unit 2: Mixtures and Solutions",
        "5.6C",
        "create solutions and compare the properties of substances before and after they are combined.",
        ["solution", "solute", "solvent", "dissolve", "physical property"],
        ["water", "salt", "sugar", "powdered drink mix", "beakers"],
        "/labs/solutions",
        "Open Solutions Lab",
        "Chapter 3 Lesson 3.2: Properties of Solutions",
    ),
    make_lesson(
        21,
        "Changes When Creating Solutions",
        "Unit 2: Mixtures and Solutions",
        "5.6C",
        "observe and explain physical-property changes that happen when solutions are formed.",
        ["solution", "dissolving", "physical state", "mass", "volume"],
        ["beakers", "water", "solutes", "graduated cylinders"],
        "/labs/solutions",
        "Open Solutions Lab",
        "Chapter 3 Lesson 3.2: Properties of Solutions",
    ),
    make_lesson(
        22,
        "Comparing Substances Before and After a Solution Forms",
        "Unit 2: Mixtures and Solutions",
        "5.6C",
        "compare mass, volume, and physical state before and after substances are combined into a solution.",
        ["mass", "volume", "physical state", "solution", "data"],
        ["digital scales", "graduated cylinders", "beakers", "water", "salt"],
        "/labs/conservation-matter",
        "Open Conservation of Matter Lab",
        "Chapter 3 Lesson 3.2: Properties of Solutions",
    ),
    make_lesson(
        23,
        "Conservation of Matter in Solutions",
        "Unit 2: Mixtures and Solutions",
        "5.6C",
        "use measurement evidence to explain that matter is conserved when a solution forms.",
        ["conservation of matter", "mass", "solution", "evidence", "measure"],
        ["digital scales", "beakers", "graduated cylinders", "salt", "water"],
        "/labs/conservation-matter",
        "Open Conservation of Matter Lab",
        "Chapter 3 Lesson 3.2: Properties of Solutions",
    ),
    make_lesson(
        24,
        "Conservation of Matter: Measuring Before and After",
        "Unit 2: Mixtures and Solutions",
        "5.6C",
        "collect and analyze measurements to show that the amount of matter stays the same.",
        ["conservation", "matter", "measurement", "mass", "model"],
        ["digital scales", "beakers", "data table", "solution materials"],
        "/labs/conservation-matter",
        "Open Conservation of Matter Lab",
    ),
    make_lesson(
        25,
        "Evidence of Particles Too Small to Be Seen",
        "Unit 2: Mixtures and Solutions",
        "5.6D",
        "illustrate how matter is made of particles too small to be seen using models and evidence.",
        ["particle", "model", "gas", "matter", "evidence"],
        ["balloon", "bag of air", "beakers", "food coloring", "models"],
        "/labs/particles",
        "Open Particle Model Lab",
        "Chapter 3 Lesson 3.3: Particles of Matter",
    ),
    make_lesson(
        26,
        "Unit 2 Performance Assessment: Mixtures, Solutions, and Particles",
        "Unit 2: Mixtures and Solutions",
        "5.6B, 5.6C, 5.6D",
        "use evidence, models, and explanations to show how mixtures, solutions, and particles behave.",
        ["mixture", "solution", "particle", "conservation of matter", "evidence"],
        ["performance task planner", "notebook", "data tables"],
        "/labs/unit2-performance",
        "Open Unit 2 Performance Game",
    ),

    # Unit 3: Force and Motion
    make_lesson(
        27,
        "Equal Forces: Pull Examples",
        "Unit 3: Force and Motion",
        "5.7A",
        "investigate how equal forces can result in no change in motion.",
        ["force", "pull", "equal forces", "motion", "position"],
        ["spring scales", "toy objects", "rope", "data table"],
        "/labs/balanced-forces",
        "Open Balanced Forces Lab",
        "Chapter 6 Lesson 6.1: Equal and Unequal Forces",
    ),
    make_lesson(
        28,
        "Equal Forces: Push Examples",
        "Unit 3: Force and Motion",
        "5.7A",
        "explain how equal pushes can balance forces acting on an object.",
        ["push", "equal forces", "balanced forces", "motion"],
        ["toy cars", "blocks", "spring scales"],
        "/labs/balanced-forces",
        "Open Balanced Forces Lab",
        "Chapter 6 Lesson 6.1: Equal and Unequal Forces",
    ),
    make_lesson(
        29,
        "Unequal Forces: Pull Examples",
        "Unit 3: Force and Motion",
        "5.7A",
        "investigate how unequal pulling forces change an object’s motion.",
        ["unequal forces", "pull", "motion", "direction", "strength"],
        ["spring scales", "objects", "rope"],
        "/labs/unequal-forces",
        "Open Unequal Forces Lab",
        "Chapter 6 Lesson 6.1: Equal and Unequal Forces",
    ),
    make_lesson(
        30,
        "Unequal Forces: Push Examples",
        "Unit 3: Force and Motion",
        "5.7A",
        "investigate how unequal pushing forces change an object’s speed or direction.",
        ["unequal forces", "push", "speed", "direction", "motion"],
        ["toy cars", "ramps", "blocks"],
        "/labs/force-strength-direction",
        "Open Force Strength and Direction Lab",
        "Chapter 6 Lesson 6.1: Equal and Unequal Forces",
    ),
    make_lesson(
        31,
        "Transfer of Mechanical Energy",
        "Unit 3: Force and Motion",
        "5.7A",
        "explain how forces can cause patterns of motion and transfer mechanical energy.",
        ["mechanical energy", "motion", "transfer", "force", "pattern"],
        ["balls", "ramps", "toy cars"],
        "/labs/mechanical-energy-transfer",
        "Open Mechanical Energy Transfer Lab",
        "Chapter 6 Lesson 6.1: Equal and Unequal Forces",
    ),
    make_lesson(
        32,
        "Mechanical Energy in Motion Systems",
        "Unit 3: Force and Motion",
        "5.7A",
        "use evidence to explain how mechanical energy is transferred in moving objects.",
        ["mechanical energy", "system", "motion", "evidence"],
        ["ramps", "cars", "measurement tools"],
        "/labs/mechanical-energy-transfer",
        "Open Mechanical Energy Transfer Lab",
    ),
    make_lesson(
        33,
        "Simple Investigation: Car on a Ramp",
        "Unit 3: Force and Motion",
        "5.7B",
        "design a simple investigation to test how force affects an object in a system.",
        ["investigation", "variable", "force", "ramp", "system"],
        ["ramps", "toy cars", "meter sticks", "data tables"],
        "/labs/ramp-investigation",
        "Open Ramp Investigation Lab",
        "Chapter 6 Lesson 6.2: Effects of Force",
    ),
    make_lesson(
        34,
        "Simple Investigation: Balloon Rocket",
        "Unit 3: Force and Motion",
        "5.7B",
        "test how force affects motion using a balloon rocket system.",
        ["force", "motion", "system", "variable", "data"],
        ["balloons", "string", "straws", "tape", "meter sticks"],
        "/labs/balloon-rocket",
        "Open Balloon Rocket Lab",
        "Chapter 6 Lesson 6.2: Effects of Force",
    ),
    make_lesson(
        35,
        "Simple Investigation: Variables and Data",
        "Unit 3: Force and Motion",
        "5.7B",
        "identify variables and collect data in a force and motion investigation.",
        ["variable", "data", "trial", "distance", "evidence"],
        ["investigation planner", "data table", "graph paper"],
        "/labs/data-graphing",
        "Open Data Graphing Lab",
    ),
    make_lesson(
        36,
        "Unit 3 Performance Task: Force and Motion Investigation",
        "Unit 3: Force and Motion",
        "5.7A, 5.7B",
        "use investigation evidence to explain how force affects motion in a system.",
        ["force", "motion", "mechanical energy", "system", "claim", "evidence"],
        ["performance task planner", "lab notebook", "materials from prior labs"],
        "/labs/ball-bounce-designer",
        "Open Investigation Designer",
    ),

    # Unit 4: Energy Transformations, Part 1
    make_lesson(
        37,
        "What Is Energy? Forms of Energy",
        "Unit 4: Energy Transformations",
        "5.8A",
        "identify different forms of energy and describe evidence that energy is present in systems.",
        ["energy", "light energy", "thermal energy", "sound energy", "mechanical energy"],
        ["image cards", "device examples", "notebook"],
        None,
        None,
        "Chapter 5 Lesson 5.1: Energy Transforms",
    ),
    make_lesson(
        38,
        "Energy Transformation in Everyday Systems",
        "Unit 4: Energy Transformations",
        "5.8A",
        "describe how energy changes from one form to another in everyday systems.",
        ["energy transformation", "system", "transfer", "transform"],
        ["device pictures", "flowchart organizer"],
        None,
        None,
        "Chapter 5 Lesson 5.1: Energy Transforms",
    ),
    make_lesson(
        39,
        "Chemical Energy in Batteries",
        "Unit 4: Energy Transformations",
        "5.8A",
        "explain that batteries store chemical energy that can be transformed into electrical energy.",
        ["chemical energy", "battery", "electrical energy", "system"],
        ["flashlight", "battery", "diagram paper"],
        None,
        None,
        "Chapter 5 Lesson 5.1: Energy Transforms",
    ),
    make_lesson(
        40,
        "Flashlight Energy Flow",
        "Unit 4: Energy Transformations",
        "5.8A",
        "model how energy in a flashlight changes from chemical energy to electrical energy to light energy.",
        ["flashlight", "chemical energy", "electrical energy", "light energy", "flowchart"],
        ["flashlight", "battery", "flowchart organizer"],
        None,
        None,
        "Chapter 5 Lesson 5.1: Energy Transforms",
    ),
    make_lesson(
        41,
        "Energy Transformation Flowchart Builder",
        "Unit 4: Energy Transformations",
        "5.8A, 5.1F",
        "construct a flowchart that shows how energy moves and changes forms in a system.",
        ["flowchart", "energy transfer", "energy transformation", "system"],
        ["flowchart template", "device cards", "notebook"],
        None,
        None,
        "Chapter 5 Lesson 5.1: Energy Transforms",
    ),
    make_lesson(
        42,
        "Energy Transformations in Multiple Devices",
        "Unit 4: Energy Transformations",
        "5.8A",
        "compare energy transformations in devices such as flashlights, buzzers, fans, and toasters.",
        ["light energy", "thermal energy", "sound energy", "mechanical energy", "electrical energy"],
        ["device images", "comparison chart"],
        None,
        None,
        "Chapter 5 Lesson 5.1: Energy Transforms",
    ),
    make_lesson(
        43,
        "Unit 4 Energy Transformation Review",
        "Unit 4: Energy Transformations",
        "5.8A",
        "use models, vocabulary, and evidence to explain energy transformations in systems.",
        ["energy", "transformation", "system", "evidence", "model"],
        ["review cards", "notebook", "CER response"],
        None,
        None,
        "Chapter 5 Lesson 5.1: Energy Transforms",
    ),

    # End of MP1
    make_lesson(
        44,
        "Flex Day: Reteach, Review, and Science Stations",
        "MP1 Review",
        "5.6A, 5.6B, 5.6C, 5.6D, 5.7A, 5.7B, 5.8A",
        "review important MP1 science ideas through stations, reteach groups, and written explanations.",
        ["review", "evidence", "model", "data", "CER"],
        ["station cards", "student notebooks", "review games"],
        "/labs/science-stations-board",
        "Open Science Stations Board",
    ),
    make_lesson(
        45,
        "1st 9 Weeks Test and Reflection",
        "MP1 Review",
        "MP1 Assessment",
        "show what I learned on the 1st 9 Weeks assessment and reflect on my strengths and next steps.",
        ["reflection", "goal", "evidence", "growth"],
        ["assessment", "reflection tracker", "notebook"],
        "/labs/reflection-tracker",
        "Open Reflection Tracker",
    ),
]

# Compatibility aliases used by different parts of the app.
first_nine_weeks = first_nine_weeks_lessons
lessons = first_nine_weeks_lessons
all_lessons = first_nine_weeks_lessons
