MP1_LAB_ARCADES = {
    "science-tools-practice": {
        "day": 2,
        "unit": "Classroom Launch",
        "title": "Science Tools Practice",
        "subtitle": "Choose the best science tool for each investigation job.",
        "mission": "Match each science task to the correct tool.",
        "mode": "tools",
        "targets": ["balance", "graduated cylinder", "thermometer", "metric ruler", "hand lens", "safety goggles"],
        "items": [
            {"name": "Measure mass in grams", "icon": "⚖️", "answer": "balance", "observation": "A balance measures mass in grams."},
            {"name": "Measure liquid volume", "icon": "🧪", "answer": "graduated cylinder", "observation": "A graduated cylinder measures volume in milliliters."},
            {"name": "Measure temperature", "icon": "🌡️", "answer": "thermometer", "observation": "A thermometer measures temperature."},
            {"name": "Measure length", "icon": "📏", "answer": "metric ruler", "observation": "A metric ruler measures length in centimeters or millimeters."},
            {"name": "Look closely at small details", "icon": "🔎", "answer": "hand lens", "observation": "A hand lens magnifies small details."},
            {"name": "Protect your eyes", "icon": "🥽", "answer": "safety goggles", "observation": "Safety goggles protect your eyes during investigations."},
        ],
    },
    "lab-safety-review": {
        "day": 1,
        "unit": "Classroom Launch",
        "title": "Lab Safety Review",
        "subtitle": "Sort safe and unsafe choices before science investigations.",
        "mission": "Classify each lab behavior as safe or unsafe.",
        "mode": "safety",
        "targets": ["safe choice", "unsafe choice"],
        "items": [
            {"name": "Wear goggles during a lab", "icon": "🥽", "answer": "safe choice", "observation": "Goggles protect your eyes."},
            {"name": "Run across the classroom with tools", "icon": "🏃", "answer": "unsafe choice", "observation": "Running with tools can hurt someone."},
            {"name": "Tell the teacher about a spill", "icon": "✋", "answer": "safe choice", "observation": "Reporting spills helps keep everyone safe."},
            {"name": "Taste an unknown material", "icon": "🚫", "answer": "unsafe choice", "observation": "Scientists do not taste unknown materials."},
            {"name": "Clean up your station", "icon": "🧽", "answer": "safe choice", "observation": "Cleaning up keeps the lab safe for others."},
        ],
    },
    "mixture-sorter": {
        "day": 17,
        "unit": "Unit 2",
        "title": "Mixture Sorter",
        "subtitle": "Create and classify mixtures using physical properties.",
        "mission": "Decide whether each example is a mixture and explain the evidence.",
        "mode": "mixture",
        "targets": ["mixture", "not a mixture"],
        "items": [
            {"name": "Sand and gravel", "icon": "🏖️", "answer": "mixture", "observation": "The materials are together but can still be separated."},
            {"name": "Trail mix", "icon": "🥨", "answer": "mixture", "observation": "The parts keep their properties and can be picked apart."},
            {"name": "Plain water", "icon": "💧", "answer": "not a mixture", "observation": "It is one material, not different materials combined."},
            {"name": "Iron filings and sand", "icon": "🧲", "answer": "mixture", "observation": "The iron and sand are combined but can be separated."},
            {"name": "A single copper wire", "icon": "🔌", "answer": "not a mixture", "observation": "It is one material."},
        ],
    },
    "separation-magnetism-size": {
        "day": 18,
        "unit": "Unit 2",
        "title": "Separation Tool Challenge",
        "subtitle": "Choose the best way to separate mixtures by magnetism or size.",
        "mission": "Match each mixture to the best separation method.",
        "mode": "separation",
        "targets": ["magnet", "screen or sieve", "hand sorting"],
        "items": [
            {"name": "Iron filings mixed with sand", "icon": "🧲", "answer": "magnet", "observation": "A magnet can pull out the iron filings."},
            {"name": "Large rocks mixed with small sand", "icon": "🪨", "answer": "screen or sieve", "observation": "A screen separates materials by size."},
            {"name": "Marbles mixed with buttons", "icon": "🔘", "answer": "hand sorting", "observation": "Large visible objects can be sorted by hand."},
            {"name": "Paper clips mixed with rice", "icon": "📎", "answer": "magnet", "observation": "The paper clips are attracted to a magnet."},
        ],
    },
    "filtration-evaporation": {
        "day": 19,
        "unit": "Unit 2",
        "title": "Filtration and Evaporation Lab",
        "subtitle": "Choose filtration or evaporation to separate materials.",
        "mission": "Pick the best separation method for each mixture.",
        "mode": "separation",
        "targets": ["filtration", "evaporation", "magnetism"],
        "items": [
            {"name": "Sand mixed with water", "icon": "🏖️", "answer": "filtration", "observation": "A filter can trap sand while water passes through."},
            {"name": "Salt dissolved in water", "icon": "🧂", "answer": "evaporation", "observation": "Water can evaporate and leave salt behind."},
            {"name": "Iron filings mixed with sand", "icon": "🧲", "answer": "magnetism", "observation": "A magnet can remove the iron filings."},
            {"name": "Gravel mixed with water", "icon": "🪨", "answer": "filtration", "observation": "A filter or screen can separate the gravel."},
        ],
    },
    "solution-maker": {
        "day": 20,
        "unit": "Unit 2",
        "title": "Solution Maker",
        "subtitle": "Identify solutes, solvents, and solutions.",
        "mission": "Classify the part of a solution.",
        "mode": "solution",
        "targets": ["solute", "solvent", "solution"],
        "items": [
            {"name": "Salt before it dissolves", "icon": "🧂", "answer": "solute", "observation": "The solute is the material that dissolves."},
            {"name": "Water in salt water", "icon": "💧", "answer": "solvent", "observation": "The solvent is the material that does the dissolving."},
            {"name": "Salt water after mixing", "icon": "🥤", "answer": "solution", "observation": "A solution forms when a solute dissolves in a solvent."},
            {"name": "Sugar before it dissolves", "icon": "🍬", "answer": "solute", "observation": "Sugar is the solute when it dissolves in water."},
        ],
    },
    "solution-change-lab": {
        "day": 21,
        "unit": "Unit 2",
        "title": "Solution Change Lab",
        "subtitle": "Observe what changes when a solution forms.",
        "mission": "Identify what the evidence shows after mixing.",
        "mode": "solution",
        "targets": ["dissolved", "not dissolved", "particles still present"],
        "items": [
            {"name": "Salt seems to disappear in water", "icon": "🧂", "answer": "dissolved", "observation": "The salt particles spread out in the water."},
            {"name": "Sand stays visible in water", "icon": "🏖️", "answer": "not dissolved", "observation": "The sand particles remain visible."},
            {"name": "Sugar water looks clear", "icon": "🍬", "answer": "particles still present", "observation": "The sugar is still there even when it cannot be seen."},
            {"name": "Pepper floats and stays visible", "icon": "⚫", "answer": "not dissolved", "observation": "Pepper does not dissolve in water."},
        ],
    },
    "before-after-solution": {
        "day": 22,
        "unit": "Unit 2",
        "title": "Before and After Solution Lab",
        "subtitle": "Compare substances before and after a solution forms.",
        "mission": "Decide what changed or stayed the same.",
        "mode": "solution",
        "targets": ["changed appearance", "matter still present", "not a solution"],
        "items": [
            {"name": "Salt disappears after stirring", "icon": "🧂", "answer": "changed appearance", "observation": "The salt changed how it looked when it dissolved."},
            {"name": "Sugar cannot be seen in water", "icon": "🍬", "answer": "matter still present", "observation": "The sugar particles are still in the solution."},
            {"name": "Gravel remains at the bottom", "icon": "🪨", "answer": "not a solution", "observation": "The gravel did not dissolve."},
            {"name": "Drink mix spreads through water", "icon": "🥤", "answer": "changed appearance", "observation": "The color spreads as particles mix with water."},
        ],
    },
    "conservation-solution": {
        "day": 23,
        "unit": "Unit 2",
        "title": "Conservation of Matter Lab",
        "subtitle": "Use mass evidence to show matter is conserved.",
        "mission": "Decide whether matter was conserved.",
        "mode": "conservation",
        "targets": ["matter conserved", "matter escaped", "need more data"],
        "items": [
            {"name": "Closed bag: 100 g before and 100 g after", "icon": "⚖️", "answer": "matter conserved", "observation": "The total mass stayed the same."},
            {"name": "Open cup: some water evaporated", "icon": "💧", "answer": "matter escaped", "observation": "Matter left the system as water vapor."},
            {"name": "No mass was measured", "icon": "❓", "answer": "need more data", "observation": "Scientists need measurements as evidence."},
            {"name": "Sealed bottle solution stayed 250 g", "icon": "🧴", "answer": "matter conserved", "observation": "In a closed system, total mass stayed the same."},
        ],
    },
    "measuring-conservation": {
        "day": 24,
        "unit": "Unit 2",
        "title": "Mass Before and After Challenge",
        "subtitle": "Compare measurements before and after mixing.",
        "mission": "Use the mass data to decide what happened.",
        "mode": "conservation",
        "targets": ["same mass", "mass decreased", "mass increased"],
        "items": [
            {"name": "50 g + 20 g became 70 g", "icon": "⚖️", "answer": "same mass", "observation": "The total mass before and after is equal."},
            {"name": "100 g became 92 g in an open container", "icon": "💨", "answer": "mass decreased", "observation": "Matter may have escaped the open system."},
            {"name": "30 g + 40 g became 70 g", "icon": "🧪", "answer": "same mass", "observation": "Mass was conserved."},
            {"name": "80 g became 85 g after extra material was added", "icon": "➕", "answer": "mass increased", "observation": "More matter was added to the system."},
        ],
    },
    "tiny-particle-model": {
        "day": 25,
        "unit": "Unit 2",
        "title": "Tiny Particle Model",
        "subtitle": "Model dissolved particles that are too small to see.",
        "mission": "Match the model to the best explanation.",
        "mode": "model",
        "targets": ["spread out particles", "visible pieces", "settled particles"],
        "items": [
            {"name": "Salt water looks clear", "icon": "✨", "answer": "spread out particles", "observation": "Dissolved particles are spread out too small to see."},
            {"name": "Sand grains in water", "icon": "🏖️", "answer": "visible pieces", "observation": "The particles are large enough to see."},
            {"name": "Mud collects at the bottom", "icon": "🟤", "answer": "settled particles", "observation": "The particles did not dissolve and settled."},
            {"name": "Sugar water tastes sweet", "icon": "🍬", "answer": "spread out particles", "observation": "Sugar particles are still present but too small to see."},
        ],
    },
    "unit2-performance": {
        "day": 26,
        "unit": "Unit 2",
        "title": "Mixtures and Solutions Review Game",
        "subtitle": "Review mixtures, solutions, separation, and conservation of matter.",
        "mission": "Choose the science concept that matches the evidence.",
        "mode": "review",
        "targets": ["mixture", "solution", "separation", "conservation"],
        "items": [
            {"name": "Salt dissolves in water", "icon": "🧂", "answer": "solution", "observation": "A solution forms when a solute dissolves in a solvent."},
            {"name": "A magnet removes iron filings", "icon": "🧲", "answer": "separation", "observation": "Magnetism can separate a mixture."},
            {"name": "Trail mix parts can be picked apart", "icon": "🥨", "answer": "mixture", "observation": "The parts keep their properties."},
            {"name": "Mass stays equal in a closed system", "icon": "⚖️", "answer": "conservation", "observation": "Matter is conserved when it does not escape."},
        ],
    },
    "equal-pull": {
        "day": 27,
        "unit": "Unit 3",
        "title": "Equal Pull Force Tug",
        "subtitle": "Model equal pull forces and balanced motion.",
        "mission": "Decide whether the forces are balanced or unbalanced.",
        "mode": "force",
        "targets": ["balanced forces", "unbalanced forces"],
        "items": [
            {"name": "10 N left pull and 10 N right pull", "icon": "↔️", "answer": "balanced forces", "observation": "Equal forces in opposite directions are balanced."},
            {"name": "8 N left pull and 12 N right pull", "icon": "➡️", "answer": "unbalanced forces", "observation": "The stronger pull changes motion."},
            {"name": "5 N left pull and 5 N right pull", "icon": "↔️", "answer": "balanced forces", "observation": "The forces are equal."},
        ],
    },
    "equal-push": {
        "day": 28,
        "unit": "Unit 3",
        "title": "Equal Push Force Challenge",
        "subtitle": "Model equal pushes from opposite directions.",
        "mission": "Classify the push forces.",
        "mode": "force",
        "targets": ["balanced forces", "unbalanced forces"],
        "items": [
            {"name": "Two students push a box equally", "icon": "📦", "answer": "balanced forces", "observation": "Equal pushes do not change the motion."},
            {"name": "One side pushes harder", "icon": "➡️", "answer": "unbalanced forces", "observation": "The box moves toward the weaker side."},
            {"name": "Same push from both sides", "icon": "↔️", "answer": "balanced forces", "observation": "The net force is zero."},
        ],
    },
    "unequal-pull": {
        "day": 29,
        "unit": "Unit 3",
        "title": "Unequal Pull Force Lab",
        "subtitle": "Predict motion when one pull is stronger.",
        "mission": "Choose the direction of motion.",
        "mode": "force",
        "targets": ["moves left", "moves right", "no change in motion"],
        "items": [
            {"name": "15 N left pull and 5 N right pull", "icon": "⬅️", "answer": "moves left", "observation": "The stronger pull is to the left."},
            {"name": "4 N left pull and 12 N right pull", "icon": "➡️", "answer": "moves right", "observation": "The stronger pull is to the right."},
            {"name": "7 N left pull and 7 N right pull", "icon": "↔️", "answer": "no change in motion", "observation": "Equal opposite forces are balanced."},
        ],
    },
    "unequal-push": {
        "day": 30,
        "unit": "Unit 3",
        "title": "Unequal Push Force Lab",
        "subtitle": "Predict motion when push forces are unequal.",
        "mission": "Choose what happens to the object.",
        "mode": "force",
        "targets": ["moves left", "moves right", "no change in motion"],
        "items": [
            {"name": "A stronger push from the left side", "icon": "➡️", "answer": "moves right", "observation": "The object moves away from the stronger push."},
            {"name": "A stronger push from the right side", "icon": "⬅️", "answer": "moves left", "observation": "The object moves away from the stronger push."},
            {"name": "Equal pushes from both sides", "icon": "↔️", "answer": "no change in motion", "observation": "The pushes are balanced."},
        ],
    },
    "mechanical-energy-transfer": {
        "day": 31,
        "unit": "Unit 3",
        "title": "Mechanical Energy Transfer Lab",
        "subtitle": "Observe how motion energy transfers between objects.",
        "mission": "Identify the energy transfer evidence.",
        "mode": "energy",
        "targets": ["energy transferred", "no energy transfer", "need more evidence"],
        "items": [
            {"name": "A moving marble hits a resting marble", "icon": "⚪", "answer": "energy transferred", "observation": "The resting marble begins moving."},
            {"name": "A ball sits still on the table", "icon": "🏀", "answer": "no energy transfer", "observation": "There is no motion interaction."},
            {"name": "A cart bumps another cart", "icon": "🛒", "answer": "energy transferred", "observation": "Motion changes after contact."},
            {"name": "You cannot see what happened", "icon": "❓", "answer": "need more evidence", "observation": "Scientists need observations to make claims."},
        ],
    },
    "motion-system": {
        "day": 32,
        "unit": "Unit 3",
        "title": "Motion System Builder",
        "subtitle": "Identify parts of a mechanical energy system.",
        "mission": "Classify the role of each part in the system.",
        "mode": "system",
        "targets": ["energy source", "moving object", "energy receiver"],
        "items": [
            {"name": "Your hand pushing a toy car", "icon": "✋", "answer": "energy source", "observation": "Your hand gives mechanical energy to the car."},
            {"name": "Toy car rolling down a ramp", "icon": "🚗", "answer": "moving object", "observation": "The car has mechanical energy because it is moving."},
            {"name": "Block hit by the car", "icon": "🧱", "answer": "energy receiver", "observation": "The block receives energy when it moves."},
        ],
    },
    "car-ramp": {
        "day": 33,
        "unit": "Unit 3",
        "title": "Car on a Ramp Lab",
        "subtitle": "Change a ramp and collect motion data.",
        "mission": "Predict how the ramp affects distance.",
        "mode": "ramp",
        "targets": ["travels farther", "travels shorter", "no change"],
        "items": [
            {"name": "Ramp gets higher", "icon": "📈", "answer": "travels farther", "observation": "A higher ramp can give the car more motion energy."},
            {"name": "Ramp gets lower", "icon": "📉", "answer": "travels shorter", "observation": "A lower ramp usually gives the car less motion energy."},
            {"name": "Ramp stays the same", "icon": "➖", "answer": "no change", "observation": "Keeping the variable the same should give similar results."},
        ],
    },
    "balloon-rocket": {
        "day": 34,
        "unit": "Unit 3",
        "title": "Balloon Rocket Launch",
        "subtitle": "Investigate force and motion with air pushing out of a balloon.",
        "mission": "Predict how the balloon rocket will move.",
        "mode": "rocket",
        "targets": ["moves forward", "moves backward", "does not move"],
        "items": [
            {"name": "Air pushes out behind the balloon", "icon": "🎈", "answer": "moves forward", "observation": "The escaping air pushes the balloon in the opposite direction."},
            {"name": "Balloon is not inflated", "icon": "🎈", "answer": "does not move", "observation": "There is no stored air to push out."},
            {"name": "More air is added to the balloon", "icon": "💨", "answer": "moves forward", "observation": "More escaping air can create a stronger push."},
        ],
    },
    "variables-data": {
        "day": 35,
        "unit": "Unit 3",
        "title": "Variables and Data Lab",
        "subtitle": "Identify variables and use data as evidence.",
        "mission": "Choose the correct investigation term.",
        "mode": "data",
        "targets": ["changed variable", "measured result", "controlled variable"],
        "items": [
            {"name": "Changing ramp height", "icon": "📈", "answer": "changed variable", "observation": "This is the variable being tested."},
            {"name": "Measuring how far the car travels", "icon": "📏", "answer": "measured result", "observation": "This is the data collected."},
            {"name": "Using the same car each trial", "icon": "🚗", "answer": "controlled variable", "observation": "This keeps the test fair."},
        ],
    },
    "force-motion-performance": {
        "day": 36,
        "unit": "Unit 3",
        "title": "Force and Motion Performance Game",
        "subtitle": "Use evidence to explain forces, motion, variables, and energy transfer.",
        "mission": "Match the evidence to the correct science idea.",
        "mode": "review",
        "targets": ["balanced force", "unbalanced force", "energy transfer", "variable"],
        "items": [
            {"name": "Equal pushes from both sides", "icon": "↔️", "answer": "balanced force", "observation": "Balanced forces do not change motion."},
            {"name": "One pull is stronger", "icon": "➡️", "answer": "unbalanced force", "observation": "Unbalanced forces change motion."},
            {"name": "A moving ball hits another ball", "icon": "⚪", "answer": "energy transfer", "observation": "Mechanical energy transfers during the collision."},
            {"name": "Ramp height is changed", "icon": "📈", "answer": "variable", "observation": "The changed factor is the variable being tested."},
        ],
    },
    "forms-of-energy": {
        "day": 37,
        "unit": "Unit 4",
        "title": "CMELTS Energy Sort",
        "subtitle": "Identify chemical, mechanical, electrical, light, thermal, and sound energy.",
        "mission": "Match each example to the form of energy.",
        "mode": "energy",
        "targets": ["chemical", "mechanical", "electrical", "light", "thermal", "sound"],
        "items": [
            {"name": "Battery stores energy", "icon": "🔋", "answer": "chemical", "observation": "Batteries store chemical energy."},
            {"name": "A moving fan blade", "icon": "🌀", "answer": "mechanical", "observation": "Moving objects have mechanical energy."},
            {"name": "Electricity in a wire", "icon": "🔌", "answer": "electrical", "observation": "Electrical energy moves through circuits."},
            {"name": "A lamp glowing", "icon": "💡", "answer": "light", "observation": "Light energy helps us see."},
            {"name": "A hot cup of cocoa", "icon": "☕", "answer": "thermal", "observation": "Thermal energy is heat energy."},
            {"name": "A ringing bell", "icon": "🔔", "answer": "sound", "observation": "Sound energy is caused by vibrations."},
        ],
    },
    "everyday-transformations": {
        "day": 38,
        "unit": "Unit 4",
        "title": "Energy Transformation Sorter",
        "subtitle": "Identify input and output energy in everyday devices.",
        "mission": "Choose the main energy transformation.",
        "mode": "energy",
        "targets": ["chemical to light", "electrical to light", "electrical to mechanical", "electrical to sound"],
        "items": [
            {"name": "Battery flashlight", "icon": "🔦", "answer": "chemical to light", "observation": "Chemical energy in the battery helps produce light."},
            {"name": "Plug-in lamp", "icon": "💡", "answer": "electrical to light", "observation": "Electrical energy changes to light energy."},
            {"name": "Electric fan", "icon": "🌀", "answer": "electrical to mechanical", "observation": "Electrical energy makes the fan blades move."},
            {"name": "Speaker", "icon": "🔊", "answer": "electrical to sound", "observation": "Electrical energy changes to sound energy."},
        ],
    },
    "battery-energy": {
        "day": 39,
        "unit": "Unit 4",
        "title": "Battery Energy Lab",
        "subtitle": "Trace chemical energy from batteries into a device.",
        "mission": "Identify the energy role of each part.",
        "mode": "energy",
        "targets": ["chemical energy", "electrical energy", "output energy"],
        "items": [
            {"name": "Energy stored in a battery", "icon": "🔋", "answer": "chemical energy", "observation": "Batteries store chemical energy."},
            {"name": "Energy moving through wires", "icon": "🔌", "answer": "electrical energy", "observation": "Electrical energy moves through a circuit."},
            {"name": "The bulb lights up", "icon": "💡", "answer": "output energy", "observation": "Light is the useful output energy."},
        ],
    },
    "flashlight-flow": {
        "day": 40,
        "unit": "Unit 4",
        "title": "Flashlight Energy Flow",
        "subtitle": "Build the energy path through a flashlight.",
        "mission": "Match each step to its energy form.",
        "mode": "flow",
        "targets": ["chemical", "electrical", "light", "thermal"],
        "items": [
            {"name": "Battery", "icon": "🔋", "answer": "chemical", "observation": "The battery stores chemical energy."},
            {"name": "Circuit wires", "icon": "🔌", "answer": "electrical", "observation": "Electrical energy flows through the circuit."},
            {"name": "Bulb shining", "icon": "💡", "answer": "light", "observation": "The bulb produces light energy."},
            {"name": "Bulb gets warm", "icon": "🔥", "answer": "thermal", "observation": "Some energy changes to thermal energy."},
        ],
    },
    "flowchart-builder": {
        "day": 41,
        "unit": "Unit 4",
        "title": "Energy Flowchart Builder",
        "subtitle": "Use arrows to show how energy changes form.",
        "mission": "Choose the correct part of an energy flowchart.",
        "mode": "flow",
        "targets": ["input energy", "transformation", "output energy"],
        "items": [
            {"name": "Battery energy before the device works", "icon": "🔋", "answer": "input energy", "observation": "Input energy starts the system."},
            {"name": "Energy changes form inside the device", "icon": "🔁", "answer": "transformation", "observation": "A transformation is a change from one energy form to another."},
            {"name": "Light from a flashlight", "icon": "💡", "answer": "output energy", "observation": "Output energy is what the device produces."},
        ],
    },
    "multiple-devices": {
        "day": 42,
        "unit": "Unit 4",
        "title": "Device Energy Detective",
        "subtitle": "Compare energy transformations in different devices.",
        "mission": "Choose the best energy transformation evidence.",
        "mode": "energy",
        "targets": ["electrical to light", "electrical to sound", "electrical to mechanical", "chemical to electrical"],
        "items": [
            {"name": "Lamp", "icon": "💡", "answer": "electrical to light", "observation": "A lamp changes electrical energy into light."},
            {"name": "Speaker", "icon": "🔊", "answer": "electrical to sound", "observation": "A speaker changes electrical energy into sound."},
            {"name": "Fan", "icon": "🌀", "answer": "electrical to mechanical", "observation": "A fan changes electrical energy into motion."},
            {"name": "Battery inside a toy", "icon": "🔋", "answer": "chemical to electrical", "observation": "A battery changes stored chemical energy into electrical energy."},
        ],
    },
    "energy-review": {
        "day": 43,
        "unit": "Unit 4",
        "title": "Energy Transformation Review",
        "subtitle": "Review energy forms, devices, and flowcharts.",
        "mission": "Match the example to the correct energy idea.",
        "mode": "review",
        "targets": ["chemical", "mechanical", "electrical", "thermal", "light", "sound"],
        "items": [
            {"name": "Food stores energy", "icon": "🍎", "answer": "chemical", "observation": "Food stores chemical energy."},
            {"name": "A rolling cart", "icon": "🛒", "answer": "mechanical", "observation": "Moving objects have mechanical energy."},
            {"name": "A working circuit", "icon": "🔌", "answer": "electrical", "observation": "Electrical energy flows through circuits."},
            {"name": "A warm object", "icon": "🔥", "answer": "thermal", "observation": "Thermal energy is heat."},
            {"name": "A glowing bulb", "icon": "💡", "answer": "light", "observation": "The bulb gives off light energy."},
            {"name": "A vibrating speaker", "icon": "🔊", "answer": "sound", "observation": "Vibrations can produce sound energy."},
        ],
    },
    "mp1-review-stations": {
        "day": 44,
        "unit": "Review",
        "title": "MP1 Review Stations Game",
        "subtitle": "Review matter, mixtures, force and motion, and energy transformations.",
        "mission": "Choose which unit matches each review clue.",
        "mode": "review",
        "targets": ["matter", "mixtures and solutions", "force and motion", "energy transformations"],
        "items": [
            {"name": "An object sinks in water", "icon": "🪨", "answer": "matter", "observation": "Sinking and floating are related to relative density."},
            {"name": "Salt dissolves in water", "icon": "🧂", "answer": "mixtures and solutions", "observation": "A solution forms when a solute dissolves in a solvent."},
            {"name": "A stronger push changes motion", "icon": "➡️", "answer": "force and motion", "observation": "Unbalanced forces change motion."},
            {"name": "A flashlight changes stored energy to light", "icon": "🔦", "answer": "energy transformations", "observation": "Energy can change from one form to another."},
        ],
    },
    "mp1-test-reflection": {
        "day": 45,
        "unit": "Review",
        "title": "Science Reflection Builder",
        "subtitle": "Reflect on strengths, growth areas, and next steps.",
        "mission": "Match each reflection clue to the best category.",
        "mode": "reflection",
        "targets": ["strength", "growth area", "next step"],
        "items": [
            {"name": "I can explain conductors and insulators", "icon": "✅", "answer": "strength", "observation": "A strength is something you can do well."},
            {"name": "I still confuse mixtures and solutions", "icon": "🧠", "answer": "growth area", "observation": "A growth area is something to practice."},
            {"name": "I will use vocabulary cards to review", "icon": "📚", "answer": "next step", "observation": "A next step is a plan for improvement."},
        ],
    },
}

DAY_TO_SLUG = {lab["day"]: slug for slug, lab in MP1_LAB_ARCADES.items()}


def get_mp1_arcade_by_slug(slug):
    return MP1_LAB_ARCADES.get(slug)


def get_mp1_arcade_for_day(day):
    try:
        day = int(day)
    except Exception:
        return None

    slug = DAY_TO_SLUG.get(day)

    if not slug:
        return None

    lab = dict(MP1_LAB_ARCADES[slug])
    lab["slug"] = slug
    lab["url"] = f"/labs/mp1/arcade/{slug}"
    return lab
